import { Router } from 'express';
import { pingRouter } from './ping.js';
import { runtimeConfigRouter } from './runtime-config.js';
import { submitAnalysisDispatchRouter } from './submit-analysis-dispatch.js';
import { validationTemplateRouter } from './validation-template.js';
import { validationCallbackRouter } from './validation-callback.js';
import { githubOAuthTokenRouter } from './github-oauth-token.js';
import { repoForkRouter } from './repo-fork.js';
import { issueCreateRouter } from './issue-create.js';
import { addTemplatePrRouter } from './add-template-pr.js';
import { archiveCollectionRouter } from './archive-collection.js';
import { batchScanStartRouter, batchScanStatusRouter } from './batch-scan-start.js';
import { validationStatusRouter } from './validation-status.js';
import { validationCancelRouter } from './validation-cancel.js';
import { analyzeTemplateRouter } from './analyze-template.js';
import { healthEnvRouter } from './health-env.js';

export const apiRouter = Router();
apiRouter.use('/ping', pingRouter);
apiRouter.use('/client-settings', runtimeConfigRouter);
apiRouter.use('/submit-analysis-dispatch', submitAnalysisDispatchRouter);
apiRouter.use('/validation-template', validationTemplateRouter);
apiRouter.use('/validation-callback', validationCallbackRouter);
apiRouter.use('/github-oauth-token', githubOAuthTokenRouter);
apiRouter.use('/repo-fork', repoForkRouter);
apiRouter.use('/issue-create', issueCreateRouter);
apiRouter.use('/add-template-pr', addTemplatePrRouter);
apiRouter.use('/archive-collection', archiveCollectionRouter);
apiRouter.use('/batch-scan-start', batchScanStartRouter);
apiRouter.use('/batch-scan-status', batchScanStatusRouter);
apiRouter.use('/validation-status', validationStatusRouter);
apiRouter.use('/validation-cancel', validationCancelRouter);
apiRouter.use('/analyze-template', analyzeTemplateRouter);
apiRouter.use('/health/env', healthEnvRouter);
