name: Build and Deploy Azure Functions v4

on:
  push:
    branches: [main]
    paths:
      - "packages/api-v4/**"
  pull_request:
    branches: [main]
    paths:
      - "packages/api-v4/**"
  workflow_dispatch:

env:
  NODE_VERSION: '20.x'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './packages/api-v4'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          
      - name: Install Dependencies
        run: |
          cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          npm install
          
      - name: Build
        run: |
          cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          npm run build
          
      - name: Test
        run: |
          cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          npm test
          
      - name: 'Deploy to Azure Functions'
        if: github.event_name != 'pull_request'
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}