name: Deploy Frontend to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'src/frontend/**'
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare artifact (exclude backup and dev folders)
        run: |
          rsync -a --delete \
            --exclude '_backup_unused/' \
            --exclude 'node_modules/' \
            --exclude 'tests/' \
            --exclude 'playwright-report/' \
            src/frontend/ _site/

      - name: Generate runtime config.json
        env:
          GH_OAUTH_CLIENT_ID: ${{ secrets.GH_OAUTH_CLIENT_ID }}
          GH_OAUTH_SCOPE: public_repo read:user
          BACKEND_BASE_URL: ${{ secrets.TD_BACKEND_BASE_URL }}
          BACKEND_FUNCTION_KEY: ${{ secrets.TD_BACKEND_FUNCTION_KEY }}
        run: |
          mkdir -p _site
          cat > _site/config.json << 'JSON'
          {
            "githubOAuth": {
              "clientId": "${GH_OAUTH_CLIENT_ID}",
              "scope": "${GH_OAUTH_SCOPE}"
            },
            "backend": {
              "baseUrl": "${BACKEND_BASE_URL}",
              "functionKey": "${BACKEND_FUNCTION_KEY}"
            }
          }
          JSON

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
