name: Template Doctor Validation Workflow
run-name: TDV ${{ inputs.run_id }}
on:
  workflow_dispatch:
    inputs:
      target_validate_template_url:
        description: 'Full URL of the template repository to validate'
        required: true
      callback_url:
        description: 'Callback URL to notify when validation is complete'
        required: false
      run_id:
        description: 'Unique ID for this validation run'
        required: true
      customValidators:
        description: 'Comma-separated list of custom validation rules'
        required: false

permissions:
  contents: read
  actions: read
  id-token: write

jobs:
  parse-repo-url:
    runs-on: ubuntu-22.04
    outputs:
      repo_urls: ${{ steps.parse_git_diff.outputs.repo_urls }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Parse input URL
        id: parse_git_diff
        run: |
          repo_urls=$(echo "${{ github.event.inputs.target_validate_template_url }}" | jq -Rsc '[split("\n") | .[]| select(.!="")]')
          echo "$repo_urls"
          echo "repo_urls=$repo_urls" >> $GITHUB_OUTPUT
        shell: bash
        continue-on-error: true

  validation:
    runs-on: ubuntu-22.04
    needs: parse-repo-url
    if: ${{ needs.parse-repo-url.outputs.repo_urls != '' }}
    strategy:
      matrix:
        repo_url: ${{ fromJson(needs.parse-repo-url.outputs.repo_urls) }}
    env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_ENV_NAME: template-doctor-${{ github.run_id }}-${{ github.run_attempt }}
      AZURE_LOCATION: eastus
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Parse repo name
        id: parse_repo_name
        run: |
          repo_name=$(echo "${{ matrix.repo_url }}" | grep -oP '(?<=https:\/\/github\.com\/)[^\/]+\/[^\/]+')
          echo "repo_name=$repo_name" >> $GITHUB_OUTPUT
          echo "repo_name_short=$(echo $repo_name | cut -d'/' -f2)" >> $GITHUB_OUTPUT
        shell: bash

      - name: Log validation info
        run: |
          echo "Starting validation for template: ${{ matrix.repo_url }}"
          echo "Run ID: ${{ github.event.inputs.run_id }}"
          echo "Custom validators: ${{ github.event.inputs.customValidators }}"
          echo "Environment name: ${{ env.AZURE_ENV_NAME }}"
          echo "Location: ${{ env.AZURE_LOCATION }}"
          echo "Callback URL: ${{ github.event.inputs.callback_url || 'None provided' }}"

      - name: Clone repo
        working-directory: ${{ runner.temp }}
        run: |
          git clone "${{ matrix.repo_url }}" template
          candidate_hooks_paths=(
            "./template/hooks"
            "./template/infra/hooks"
            "./template/scripts"
            "./template/deploy/aca/scripts"
            "./template/deploy/aks/scripts"
            "./template/deploy/app-service/scripts"
          )
          for hooks_path in "${candidate_hooks_paths[@]}"; do
            if [ -d "$hooks_path" ] && [ "$(ls -A $hooks_path/*.sh 2>/dev/null)" ]; then
              chmod +x $hooks_path/*.sh
              echo "Executable permissions set for .sh files in $hooks_path"
            fi
          done

      - name: Check for Terraform
        id: check_terraform
        run: |
          if [[ -f "${{ runner.temp }}/template/infra/main.tf" ]]; then
            echo "RUN_AZD_UP=false" >> $GITHUB_OUTPUT
          else
            echo "RUN_AZD_UP=true" >> $GITHUB_OUTPUT
          fi

      - id: validation
        uses: microsoft/template-validation-action@Latest
        with:
          workingDirectory: ${{ runner.temp }}/template
        env:
          REPOSITORY_NAME: ${{ steps.parse_repo_name.outputs.repo_name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATORS: ${{ github.event.inputs.customValidators || 'azd-provision,ps-rule' }}
        continue-on-error: true

      - name: Handle UnmatchedPrincipalType
        run: |
          LOG_FILE="${{ steps.validation.outputs.resultFile }}"
          if [ -f "$LOG_FILE" ] && grep -q "UnmatchedPrincipalType" "$LOG_FILE"; then
            echo "⚠️ Caught UnmatchedPrincipalType, ignoring error"
            # Optionally, you could also annotate the summary here
          fi

      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.parse_repo_name.outputs.repo_name_short }}-validation-result
          path: ${{ steps.validation.outputs.resultFile }}

      - name: Check result
        id: check_result
        run: |
          if grep -q "NON-CONFORMING" "${{ steps.vali
